server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: case-service # 路由ID
          uri: lb://case-service # 路由转发地址
          predicates: # 断言配置
            - Path=/categories/**, /diseases/**, /medcases/**, /medcases , /inspections/**, /medicines/**, /operations/**,/room-assets/**, /rooms/**, /users/**
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exams, /exams/**, /papers, /papers/**, /answer-sheets/**,/questions/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/files/**, /files
        - id: gpt-service
          uri: lb://gpt-service
          predicates:
            - Path=/gpts/**
      default-filters:
        - PrefixPath=/api
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS