server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://47.103.131.161:3306/vph_case?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: case-service

  cloud:
    nacos: # nacos 配置
      server-addr: localhost:8848
mybatis:
  type-aliases-package: cn.vph.case.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数 可用JMeter做压测 从而选择更加合适的值
    max-connections-per-route: 50 # 单路径最大连接数

#      defaultZone: http://127.0.0.1:10086/eureka