server:
  port: 8085
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://47.103.131.161:3306/vph_medcase?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MySQLPaSsWord89h
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: file-service
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  redis:
    host: 47.103.131.161
    port: 6379
    timeout: 1000
    password: Re1d1sPssw0rd
  cloud:
    nacos:
      server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB
      enabled: false
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

swagger:
  enable: true
#      defaultZone: http://127.0.0.1:10086/eureka
vph:
  aspect:
    enable: false
  file:
    path: E:/vph/files/