server:
  port: 8085
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://47.103.131.161:3306/vph_file?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MySQLPaSsWord89h
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: file-service
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  # Redis
  redis:
    host: 47.103.131.161
    port: 6379
    timeout: 1000
    password: Re1d1sPssw0rd
  cloud:
    nacos: # nacos 配置
      server-addr: 123.60.7.212:8848
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB
      enabled: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://123.60.7.212:9999
    discovery-client-enabled: false
mybatis:
  type-aliases-package: cn.vph.file.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数 可用JMeter做压测 从而选择更加合适的值
    max-connections-per-route: 50 # 单路径最大连接数

swagger:
  enable: true
#      defaultZone: http://127.0.0.1:10086/eureka

vph:
  aspect:
    enable: true
  file:
    path: /home/vph_files/

ffmpeg:
  path: /usr/bin/ffmpeg