server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vph_login?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: cn.vph.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka