server:
  port: 8088
  servlet:
    context-path: /api
spring:
  application:
    name: common
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 47.103.131.161
    port: 6379
    timeout: 1000
    password: Re1d1sPssw0rd
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
