server:
  port: 8083
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://47.103.131.161:3306/vph_exam?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQLPaSsWord89h
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: exam-service
  cloud:
    nacos:
      server-addr: localhost:8848
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
mybatis:
  type-aliases-package: cn.vph.exam.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.vph: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

swagger:
  enable: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka